services:
  usersdb:
    container_name: users_db
    image: postgres:16.4
    volumes:
      - db-vol1:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
      POSTGRES_DB: users
  authorsdb:
    container_name: authors_db
    image: postgres:16.4
    volumes:
      - db-vol3:/var/lib/postgresql/data
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_USER: authors
      POSTGRES_PASSWORD: authors
      POSTGRES_DB: authors

  conferencesdb:
    container_name: conferences_db
    image: postgres:16.4
    volumes:
      - db-vol2:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_USER: conferences
      POSTGRES_PASSWORD: conferences
      POSTGRES_DB: conferences

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-management
    environment:
      - RABBITMQ_DEFAULT_USER=caia
      - RABBITMQ_DEFAULT_PASS=caia
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  db-vol1:
    external: false
  db-vol2:
    external: false
  db-vol3:
    external: false
