# spring:
#   application:
#     name: caia-gateway
#   config:
#     import: optional:configserver:http://localhost:8888
#   cloud:
#     gateway:
#       globalcors:
#         cors-configurations:
#           "[/**]": # Aplicar CORS a todas las rutas
#             allowedOrigins: "http://localhost:3000" # Origen permitido, puedes agregar más URLs
#             allowedMethods:
#               - GET
#               - POST
#               - PUT
#               - DELETE
#             allowedHeaders:
#               - "*"
#             allowCredentials: true
#       routes:
#         - id: caia-users
#           uri: lb://CAIA-USERS
#           predicates:
#             - Path=/api/users/***
#           filters:
#             - AuthenticationFilter

#         - id: caia-conferences
#           uri: lb://CAIA-CONFERENCES
#           predicates:
#             - Path=/api/conferences/***
#           filters:
#             - AuthenticationFilter

#         - id: caia-papers
#           uri: lb://CAIA-PAPERS
#           predicates:
#             - Path=/api/papers/***
#           filters:
#             - AuthenticationFilter

#         - id: caia-reviewers
#           uri: lb://CAIA-REVIEWERS
#           predicates:
#             - Path=/api/reviewers/***
#           filters:
#             - AuthenticationFilter
#     discovery:
#       locator:
#         enabled: true
# eureka:
#   instance:
#     instance-id: ${spring.application.name}:${random.uuid}
#     prefer-ip-address: true
#   client:
#     serviceUrl:
#       defaultZone: http://caia-eureka:8761/eureka

# security:
#   jwt:
#     key:
#       private: holamundo
#     user:
#       generator: caia-server

# server:
#   port: 8080
spring:
  application:
    name: caia-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]": # Aplicar CORS a todas las rutas
            allowedOrigins: "http://localhost:3000" # Origen permitido, puedes agregar más URLs
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: caia-users
          uri: lb://CAIA-USERS
          predicates:
            - Path=/api/users/**
          filters:
            - AuthenticationFilter

        - id: caia-conferences
          uri: lb://CAIA-CONFERENCES
          predicates:
            - Path=/api/conferences/**
          filters:
            - AuthenticationFilter

        - id: caia-papers
          uri: lb://CAIA-PAPERS
          predicates:
            - Path=/api/papers/**
          filters:
            - AuthenticationFilter

        - id: caia-reviewers
          uri: lb://CAIA-REVIEWERS
          predicates:
            - Path=/api/reviewers/**
          filters:
            - AuthenticationFilter
    discovery:
      locator:
        enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    key:
      private: holamundo
    user:
      generator: caia-server

server:
  port: 8080
