# spring:
#   config:
#     import: optional:configserver:http://localhost:8888
#   application:
#     name: caia-reviewers
#   jpa:
#     database-platform: org.hibernate.dialect.PostgreSQLDialect
#     show-sql: true
#     hibernate:
#       ddl-auto: create
#     properties:
#       hibernate:
#         "[format_sql]": true
#   datasource:
#     url: jdbc:postgresql://reviewersdb:5432/reviewers
#     username: reviewers
#     password: reviewers
#   rabbitmq:
#     host: rabbitmq
#     port: 5672
#     username: caia
#     password: caia

# rabbitmq:
#   queue:
#     name: caia-reviewers-queue
#   exchange:
#     name: caia.reviewers.exchange
#   routing:
#     key: caia.reviewers.routing.key

# server:
#   port: 8094
#   servlet:
#     context-path: /api/reviewers

# eureka:
#   instance:
#     hostname: caia-eureka
#     instance-id: ${spring.application.name}:${random.uuid}
#     prefer-ip-address: true
#   client:
#     serviceUrl:
#       defaultZone: http://caia-eureka:8761/eureka

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: caia-reviewers
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        "[format_sql]": true
  datasource:
    url: jdbc:postgresql://localhost:5436/reviewers
    username: reviewers
    password: reviewers
  rabbitmq:
    host: localhost
    port: 5672
    username: caia
    password: caia

rabbitmq:
  queue:
    name: caia-reviewers-queue
  exchange:
    name: caia.reviewers.exchange
  routing:
    key: caia.reviewers.routing.key

server:
  port: 8094
  servlet:
    context-path: /api/reviewers

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
