spring:
  application:
    name: caia-users
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: users
    password: users
  rabbitmq:
    host: localhost
    port: 5672
    username: caia
    password: caia

rabbitmq:
  queue:
    name: caia-users-queue
  exchange:
    name: caia.users.exchange
  routing:
    key: caia.users.routing.key

server:
  port: 8093
  servlet:
    context-path: /api/users

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    key:
      private: holamundo
    user:
      generator: caia-server
