spring:
  application:
    name: caia-authors
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/authors
    username: authors
    password: authors
  rabbitmq:
    host: localhost
    port: 5672
    username: caia
    password: caia

rabbitmq:
  queue:
    name: caia-users-queue
  exchange:
    name: caia.users.exchange
  routing:
    key: caia.users.routing.key

server:
  port: 8091
  servlet:
    context-path: /api/authors

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka