spring:
  application:
    name: caia-conferences
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5435/conferences
    username: conferences
    password: conferences
  rabbitmq:
    host: localhost
    port: 5672
    username: caia
    password: caia

rabbitmq:
  queue:
    name: caia-conferences-queue
  exchange:
    name: caia.conferences.exchange
  routing:
    key: caia.conferences.routing.key

server:
  port: 8092
  servlet:
    context-path: /api/conferences

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
